### PR TITLE
Polyfill for equalTo constraint specializations

### PR DESCRIPTION
**Pull request by mergeMarc**
This PR adds the **EqualToSpecializations Trait** that adds polyfills for the in PHPUnit 9.0.0 introduced methods equalToCanonicalizing, equalToIgnoringCase and equalToWithDelta.

Since PHPUnit Version 9.0.0 **equalTo** constraints got their own specializations to replicate the assertEquals specializations. (see https://github.com/sebastianbergmann/phpunit/commit/43c01a4e0c74a4bf019a8d879bced5146af2fbb6) The usage of equalTo with these parameters never got deprecated and also had no replacement until the functionality was removed (see https://github.com/sebastianbergmann/phpunit/commit/e470a3ae6ce94b4db681f579a1012c44f473e6ae).
This means that test cases that want to use equalTo with additional configuration cannot be written to work with both PHPUnit 8 (or older) and PHPUnit 9 without the use of a polyfill.

### CODE REVIEW

**Comment by mergeMarc** [comment]
I totally understand. I didn't find other people mentioning this issue anywhere so usage is probably not so wide spread.

I need to use it with PHPUnit [Mock Objects](https://phpunit.readthedocs.io/en/9.5/test-doubles.html#mock-objects). To check parameters that are passed to a mocked method call one needs to use a `Constraint` instead of the usual asserting of a value right away (see [docs example](https://phpunit.readthedocs.io/en/9.5/test-doubles.html#test-doubles-mock-objects-examples-subjecttest-php)).

#### Example:
In this excerpt of a simple test case I check if my main application uses my "PersistenceInterface" correctly. I need to include the delta here since the DateTime value of my "Day" will always be off by a few milliseconds. If I run the first version in PHPUnit 9 the test will always fail since the delta is not considered (`equalTo` only accepts one parameter since v9).

*PHPUnit < 9*
```php
$today = new Day($todayDate, $todaysWeather);
$storage = $this->createMock(PersistenceInterface::class);
$storage->expects($this->once())
            ->method('updateDay')
            ->with($this->equalTo($today, 10));
...
```
*PHPUnit >= 9*
```php
$today = new Day($todayDate, $todaysWeather);
$storage = $this->createMock(PersistenceInterface::class);
$storage->expects($this->once())
            ->method('updateDay')
            ->with($this->equalToWithDelta($today, 10));
...
```

**Comment by jrfnl** [comment]
@mergeMarc Thanks for that additional information. Makes sense to me and I'm happy to include it.

There are a few more (minor) changes needed for this PR to be complete. I'd be happy to make those or give you feedback to allow you make them. What would you prefer ?

**Comment by mergeMarc** [comment]
@jrfnl Feel free to commit those changes. I would also be available to make them if they require more work. Thank you.

**Comment by jrfnl** [comment]
@mergeMarc No, nothing major. I've just pushed the commit and will give you a moment to look it over.

One of us will still need to rebase the PR to make it mergable.

**Comment by jrfnl** [comment]
Ended up adding two more touch up commits. Will stop looking now ;-) (and will squash on merge or rebase).

**Comment by jrfnl** [comment]
Rebased on `develop` to make the PR mergable. Not new changes.

**Review by jrfnl — APPROVED** [review]
@mergeMarc Thanks a lot for this PR. Great contribution and well done on the completeness of the PR. This new feature will be included in the next release.

**Pull request merged**
